name: flutter_alone
description: "Flutter desktop application single instance plugin"
version: 1.0.0
homepage: https://github.com/kihyun1998/flutter_alone
repository: https://github.com/kihyun1998/flutter_alone

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: FlutterAlonePluginCApi